# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ dev/fast_sync_develop ]
  pull_request:
    branches: [ dev/fast_sync_develop ]

jobs:
  build:
    # if: github.repository_owner == 'telosprotocol' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize' || github.event_name == 'pushed')
    # if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event_name == 'push'
    runs-on: [self-hosted, Linux, X64]
    
    # for ci telos only
    steps:
      - name: Print event
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Sync submodule
        run: git submodule sync --recursive
        
      - name: Update submodule
        run: git submodule update --init --force --recursive

      - name: Build XTOP DEBUG
        run: |
          bash .github/scripts/build_xtop.sh "test build_ci"

      - name: UnitTest
        run: |
          bash .github/scripts/test_ut.sh

      - name: TEST XTOP AllInOne
        env:
          RUN_NUM: ${{ github.run_number }}
        run: |
          bash .github/scripts/test_xtop_allinone.sh "$RUN_NUM"

      - name: Notify
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: topqa@topnetwork.org
          password: ${{ secrets.PSWD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: aries.zhang@topnetwork.org
          from: topqa
          secure: true
          attachments: ./ut_report/report.tar.gz
